// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrxIo9PijrfZM3kkM_8RbzyKs0_jF0Ku4',
    appId: '1:617206699665:web:6921e694af321af3249130',
    messagingSenderId: '617206699665',
    projectId: 'imagine-x-93a59',
    authDomain: 'imagine-x-93a59.firebaseapp.com',
    storageBucket: 'imagine-x-93a59.firebasestorage.app',
    measurementId: 'G-YVRF69JJNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe3lDNnR-jUem9_bjNjh-olYioBu1uriM',
    appId: '1:617206699665:android:c2b9bc5537102017249130',
    messagingSenderId: '617206699665',
    projectId: 'imagine-x-93a59',
    storageBucket: 'imagine-x-93a59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc0nxsGQjbfaqbhQkP8oAt2-WbKh1vmFc',
    appId: '1:617206699665:ios:cf517c2d2ad80b46249130',
    messagingSenderId: '617206699665',
    projectId: 'imagine-x-93a59',
    storageBucket: 'imagine-x-93a59.firebasestorage.app',
    iosBundleId: 'com.smartslides.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc0nxsGQjbfaqbhQkP8oAt2-WbKh1vmFc',
    appId: '1:617206699665:ios:fa420ac97e01d5dc249130',
    messagingSenderId: '617206699665',
    projectId: 'imagine-x-93a59',
    storageBucket: 'imagine-x-93a59.firebasestorage.app',
    iosBundleId: 'com.example.infography',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrxIo9PijrfZM3kkM_8RbzyKs0_jF0Ku4',
    appId: '1:617206699665:web:27e3c81a94a250b7249130',
    messagingSenderId: '617206699665',
    projectId: 'imagine-x-93a59',
    authDomain: 'imagine-x-93a59.firebaseapp.com',
    storageBucket: 'imagine-x-93a59.firebasestorage.app',
    measurementId: 'G-SFPCLD1314',
  );
}
